export const makeResponsiveClasses = (str: string, attr: string) => {
  if (str) {
    return str
      .split(' ')
      .filter((s) => s)
      .map((s) => {
        const strs = s.split(':');
        return strs.length === 1 ? `${attr}-${strs[0]}` : `${strs[0]}:${attr}-${strs[1]}`;
      })
      .join(' ');
  }
};

const styleTexts = [
  'bg-indigo-600',
  'bg-gray-500',
  'bg-green-500',
  'bg-red-500',
  'bg-yellow-400',
  'bg-blue-300',
  'bg-pink-300',
  'bg-purple-300',
  'bg-gray-300',
  'bg-white',
  'bg-black',
  'text-indigo-600',
  'text-gray-500',
  'text-green-500',
  'text-red-500',
  'text-yellow-400',
  'text-blue-300',
  'text-pink-300',
  'text-purple-300',
  'text-gray-300',
  'text-white',
  'text-black',
  'border-indigo-600',
  'border-gray-500',
  'border-green-500',
  'border-red-500',
  'border-yellow-400',
  'border-blue-300',
  'border-pink-300',
  'border-purple-300',
  'border-gray-300',
  'border-white',
  'border-black',
  'ring-indigo-600',
  'ring-gray-500',
  'ring-green-500',
  'ring-red-500',
  'ring-yellow-400',
  'ring-blue-300',
  'ring-pink-300',
  'ring-purple-300',
  'ring-gray-300',
  'ring-white',
  'ring-black',
  'flex-col',
  'flex-row',
  'justify-start',
  'justify-end',
  'justify-center',
  'justify-between',
  'items-start',
  'items-end',
  'items-center',
  'content-start',
  'content-end',
  'content-center',
  'content-between',
  'grid-cols-1',
  'grid-cols-2',
  'grid-cols-3',
  'grid-cols-4',
  'gap-0',
  'gap-1',
  'gap-2',
  'gap-3',
  'auto-cols-fr',
];
